[build-system]
requires = ["setuptools==65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ubrobot"
version = "0.0.1"
authors = [
  { name = "Xiaowei Zhao", email = "mathzxw2002@gmail.com" }
]
description = "UBRobot"
requires-python = ">=3.10"

dependencies = [
	# Core dependencies
	"numpy>=2.0.1",
  	"pandas==2.3.3",
  	"mergedeep==1.3.4",
  	"draccus==0.10.0",
  	"fsspec==2025.2.0",
  	"dill==0.3.7",
  	"cmake==4.1.3",
  	"av==15.1.0",
  	"accelerate==1.11.0",
  	"opencv-python-headless==4.10.0.82",
  	"gymnasium==1.2.2",
  	"diffusers==0.31.0",
  	"datasets==4.1.1",
  	"transformers==4.36.2",
	"uvicorn==0.17.5",
  	"gradio==4.40.0",
  	"pydantic==2.10.6",
  	"httpx==0.27.2",
  	"librosa==0.11.0",
  	"scikit-learn==1.7.2",
  	"numba==0.63.1",
  	"pynndescent==0.6.0",
	"qwen_vl_utils",
	"pybind11",
	"modelscope_studio>=0.5.2, < 1.0",
	"websockets<16.0,>=10.0",
	"gradio-client >= 1.2.0",
	"eval_type_backport",
	"urllib3>=1.25.8",
	"soundfile==0.12.1",
	"tqdm==4.66.6",
	"threadpoolctl==3.3.0",
	"anyio==4.12.1",
	"soxr==0.4.0",
	"mpmath==1.2.1",
	"scipy==1.15.2",
	"ffmpeg-python==0.2.0",
	"decorator==5.2.1",
	"dashscope==1.25.5",
	"funasr==1.1.6",
	"aliyun-python-sdk-core==2.15.0",
	"cryptography==41.0.0",
	"umap-learn==0.5.3",
	"contourpy==1.3.1",
	"six==1.16.0",
	"shellingham==1.5.2",
	"oss2==2.13.0",
	#"torchaudio==2.1.0",
	"openai==1.43.0",
	"fastapi",
	"modelscope==1.19.2",
	"huggingface_hub<0.36.0,>=0.34.2",
	
	"pyzmq", 
	"viser<=0.2.20",
	"yourdfpy",
	"python-can==4.4.0",
	"piper_sdk",
	"pygame<2.6.2",
	"casadi==3.7.0",
	"eigenpy>=2.9.0",
	"rerun_sdk==0.26.0",
	"sentry_sdk==2.46.0",
	"lerobot==0.4.2",
	"matplotlib>=3.9.0",
	"imageio==2.36.0",
	"imageio-ffmpeg==0.5.1",
	"ftfy==6.2.3",
	"pillow==10.4.0",
	"gym==0.23.1",

	"rospkg",
	"PyQt5-sip",
	"empy",
	"open3d",
	"transforms3d",
	"pyrealsense2",
	# remote git resource
	

]

[project.scripts]

[tool.setuptools.packages.find]
where = ["src"]
