[build-system]
requires = ["setuptools==65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ubrobot"
version = "0.0.1"
authors = [
  { name = "Xiaowei Zhao", email = "mathzxw2002@gmail.com" }
]
description = "UBRobot"
requires-python = ">=3.8"

dependencies = [
	# Core dependencies
	"qwen_vl_utils",
	"pybind11",
	"gradio>=4.40.0",
	"modelscope_studio>=0.5.2, < 1.0",
	"websockets<16.0,>=10.0",
	"gradio-client >= 1.3.0",
	"pydantic==2.10.6",
	"eval_type_backport",
	"urllib3>=1.25.8",
	#"packaging==21.3",
	"transformers<=4.36.2, >=4.34.0",
	"soundfile",
	"ffmpeg-python==0.2.0",
	"dashscope",
	"funasr==1.1.6",
	"aliyun-python-sdk-core==2.13.0",
	"umap-learn==0.5.3",
	"oss2==2.13.0",
	"torchaudio==2.1.0",
	"openai==1.43.0",
	"fastapi",
	"modelscope==1.19.2",
	"httpx==0.27.2",
	"huggingface_hub<0.36.0,>=0.34.2",
	#"tokenizers>=0.15.0",
	
	"scipy", 
	"viser",
	"yourdfpy",
	"python-can==4.4.0",
	"piper_sdk",
	"pygame<2.6.2",
	"numpy<=1.26.0",
	"casadi",
	#"lerobot @ git+https://github.com/huggingface/lerobot.git",

	"matplotlib",
	"imageio==2.35.0",
	"imageio-ffmpeg==0.5.0",
	"ftfy==6.2.3",
	"diffusers==0.35.2",
	"accelerate==1.0.1",
	"opencv-python==4.10.0.82",
	"pillow==10.4.0",
	"gym==0.23.1",

	"rospkg",
	"PyQt5-sip",
	"empy",
	"ultralytics==8.2.89",
	"open3d",
	"transforms3d",
	"eigenpy",
	"pytracik",
	#"unitree_sdk2py",
	# remote git resource
	#"unitree_sdk2py @ git+https://github.com/unitreerobotics/unitree_sdk2_python.git"
	

]

[project.scripts]

[tool.setuptools.packages.find]
where = ["src"]
