[build-system]
requires = ["setuptools==65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ubrobot"
version = "0.0.1"
authors = [
  { name = "Xiaowei Zhao", email = "mathzxw2002@gmail.com" }
]
description = "UBRobot"
requires-python = ">=3.8"

dependencies = [
	# Core dependencies
	"qwen_vl_utils",
	"gradio>=4.40.0",
	"modelscope_studio>=0.5.2, < 1.0",
	"websockets>=13.1, <16.0.0",
	"gradio-client >= 1.3.0",
	"pydantic==2.10.6",
	"eval_type_backport",
	"urllib3>=1.25.8",
	"packaging==21.3",
	"transformers>=4.34.0",
	"soundfile",
	"ffmpeg-python==0.2.0",
	"dashscope",
	"funasr==1.1.6",
	"aliyun-python-sdk-core==2.13.0",
	"umap-learn==0.5.3",
	"oss2==2.13.0",
	"torchaudio==2.1.0",
	"openai==1.43.0",
	"fastapi",
	"modelscope==1.19.2",
	"httpx==0.27.2",
	"pybind11 >= 2.10.0",
	
	"scipy", 
	"viser",
	"yourdfpy",
	"python-can",
	"piper_sdk",
	"pygame<2.6.2",
	"numpy<=1.26.0",
	"casadi",

	# remote git resource
	"pytracik @ git+https://github.com/mathzxw2002/pytracik.git",
	#"unitree_sdk2py @ git+https://github.com/unitreerobotics/unitree_sdk2_python.git"
	

]

[project.scripts]

[tool.setuptools.packages.find]
where = ["src"]
